# Generated by Django 3.2.2 on 2021-06-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='work_user',
            new_name='user',
        ),
    ]
